### ISSUE TITLE
differences vs optuna

### ISSUE THREAD

**Issue by tsinggggg** [c-bata/goptuna#129]
May I ask what is the main difference between optuna and goptuna except goptuna is written in GO?

**Comment by c-bata** [comment]
Optuna provides a lot of integrations for lightgbm, tensorflow, etc. But Goptuna provides no integrations for other machine learning libraries written in Go (ex: Gorgonia, golearn) for now.

In terms of algorithms, Goptuna does not support Hyperband even though Optuna supports it. And GP based bayesian optimization support is experimental in Goptuna.

In terms of design, Goptuna heavily inspired by Optuna. So the design is quite similar with Optuna.

**Comment by c-bata** [comment]
If your question is not resolved, please reopen this.
