### ISSUE TITLE
goptuna is not compiling using gollvm. asm level bugs caught

### ISSUE THREAD

**Issue by advancedwebdeveloper** [c-bata/goptuna#154]
Hi.
I have built and is able to use [gollvm](https://go.googlesource.com/gollvm/).

When I tried to build your package - I caught such bugs:

> $ go get -u github.com/c-bata/goptuna/tpe
> # gonum.org/v1/gonum/internal/asm/f64
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s: Assembler messages:
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:10: Error: no such instruction: `text ·L1Norm(SB),NOSPLIT,$0'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:11: Error: junk `(FP)' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:11: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:12: Error: junk `(FP)' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:12: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:13: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:14: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:15: Error: too many memory references for `pxor'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:16: Error: too many memory references for `pxor'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:17: Error: too many memory references for `pxor'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:18: Error: too many memory references for `pxor'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:19: Error: too many memory references for `pxor'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:20: Error: too many memory references for `pxor'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:21: Error: too many memory references for `pxor'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:22: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:24: Error: too many memory references for `movq'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:25: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:26: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:27: Error: invalid character '=' in operand 1
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:31: Error: junk `(AX*8)' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:31: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:32: Error: junk `(SI)(AX*8)' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:32: Error: too many memory references for `movups'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:33: Error: junk `(SI)(AX*8)' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:33: Error: too many memory references for `movups'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:34: Error: junk `(SI)(AX*8)' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:34: Error: too many memory references for `movups'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:35: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:36: Error: too many memory references for `addpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:37: Error: too many memory references for `addpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:38: Error: too many memory references for `addpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:39: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:40: Error: too many memory references for `subpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:41: Error: too many memory references for `subpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:42: Error: too many memory references for `subpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:43: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:44: Error: too many memory references for `maxpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:45: Error: too many memory references for `maxpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:46: Error: too many memory references for `maxpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:47: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:48: Error: too many memory references for `movaps'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:49: Error: too many memory references for `movaps'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:50: Error: too many memory references for `movaps'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:51: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:52: Error: bad expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:52: Error: junk `} while --CX>0' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:55: Error: too many memory references for `addpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:56: Error: too many memory references for `addpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:57: Error: too many memory references for `addpd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:60: Error: too many memory references for `movaps'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:61: Error: invalid character '=' in operand 3
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:62: Error: too many memory references for `addsd'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:63: Error: operand size mismatch for `cmp'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:64: Error: invalid character '=' in operand 1
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:67: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:68: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:72: Error: junk `(AX*8)' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:72: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:73: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:74: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:75: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:76: Error: invalid character '=' in operand 2
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:77: Error: bad expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:77: Error: junk `i++' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:78: Error: bad expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:78: Error: junk `} while --CX>0' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:81: Warning: `X0' is not valid here (expected `(%rsi)')
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:81: Error: junk `(FP)' after expression
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:81: Warning: `sum+24(FP)' is not valid here (expected `(%rdi)')
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:52: Error: invalid operands (.text and *ABS* sections) for `/'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:52: Error: division by zero
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:77: Error: invalid operands (*UND* and *ABS* sections) for `/'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:77: Error: division by zero
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:78: Error: invalid operands (.text and *ABS* sections) for `/'
> go/src/gonum.org/v1/gonum/internal/asm/f64/abssum_amd64.s:78: Error: division by zero
>

It seems that your asm mix-ins are not suitable to LLVM oriented back-end. Or I am wrong?
In any case: I suspect that it should be re-designed, to work with gollvm.

Ivan 
>

**Comment by c-bata** [comment]
I think this is not a bug. As the following comment, you need to use `noasm` build tag.
https://github.com/gonum/gonum/issues/1452#issuecomment-692080376

**Comment by advancedwebdeveloper** [comment]
Please explain how

**Comment by c-bata** [comment]
Sorry. gollvm is not installed in my laptop. So I cannot explain the detail steps.

**Comment by advancedwebdeveloper** [comment]
I could archive my pre-compile "release" build of gollvm, targeting Ubuntu 20. Would that help?

**Comment by c-bata** [comment]
No I don't have the time to explain how to compile with build tags.
