### ISSUE TITLE
Benchmarking tool like sile/kurobako.

### ISSUE THREAD

**Issue by c-bata** [c-bata/goptuna#64]
It seems to be useful to check  the efficiency of optimization algorithm like [sile/kurobako](https://github.com/sile/kurobako).

* nasbench
    * https://arxiv.org/abs/1902.09635
    * https://github.com/automl/nas_benchmarks
* sigopt/evalset
    * https://github.com/sigopt/evalset
* hpobench
    * https://arxiv.org/abs/1905.04970

**Comment by sile** [comment]
Sounds good.
BTW, if you want to use `kurobako` to benchmark `goptuna`, I can help you (e.g., creating a library to implement solvers and problems in Golang).

**Comment by c-bata** [comment]
Wow. That would be so helpful, thank you!

Is there something information that I can provide in order for you to implement solvers and problems?

**Comment by sile** [comment]
👍 

---

> Is there something information that I can provide in order for you to implement solvers and problems?

Thanks. I'll try implementing a goptuna based solver in a few days. If I encounter any troubles related to  goptuna, I will ask you questions here.

**Comment by sile** [comment]
**FYI**

The first version of [kurobako-go](https://github.com/sile/kurobako-go) was worked (this is still under development though).
```console
$ cargo install -f kurobako

$ git clone https://github.com/sile/kurobako-go
$ cd kurobako-go/examples/goptuna-solver

$ RANDOM_SOLVER=$(kurobako solver random)
$ GOPTUNA_SOLVER=$(kurobako solver command go run main.go)
$ ACKLEY_PROBLEM=$(kurobako problem sigopt --dim 5 ackley)

$ kurobako studies --solvers $RANDOM_SOLVER $GOPTUNA_SOLVER --problems $ACKLEY_PROBLEM --repeats 100 --budget 100 | kurobako run --parallelism 4 > result.json
(ALL) [00:00:06] [STUDIES    200/200 100%] [ETA  0s] done

$ cat result.json | kurobako plot curve --errorbar
(PLOT) [00:00:00] [1/1 100%] [ETA  0s] done (dir="images/curve/")
```

![sigopt-evalset-ackley-dim-5-68c60185d14a19127ab4eca100424b9c646f2663935fade3d1c37cecae8186d4](https://user-images.githubusercontent.com/181413/71447891-e7192e00-2777-11ea-84de-569c64e1596f.png)

**Comment by sile** [comment]
BTW, looking at the above result, goptuna seems to always use the fixed random seed for the inner random sampling of TPE even when users specified a non default seed to `tpe.NewSampler()` method (see: https://github.com/sile/kurobako-go/blob/master/examples/goptuna-solver/main.go#L11).

**Comment by c-bata** [comment]
Amazing!! I'll check the implementation of kurobako-go.

> BTW, looking at the above result, goptuna seems to always use the fixed random seed for the inner random sampler of TPE even when users specified a non default seed to `tpe.NewSampler()` method (see: https://github.com/sile/kurobako-go/blob/master/examples/goptuna-solver/main.go#L11).

Thank you for reporting! I'll fix this at #66.

**Comment by sile** [comment]
>  I'll check the implementation of kurobako-go.

Thanks. Since this is my first Go project, there could be some weird points in the code. Any comments are welcome!

**Comment by c-bata** [comment]
Hi @sile, sorry for my late reply.

I read the code of kurobako-go and started to use at #71, then found no weird points in your code. Good job!
For my use-cases, it can be helpful that if I can customize `Specification.name` because I want to compare multiple algorithms. So please check the PR I sent to https://github.com/sile/kurobako-go/pull/2.

I will merge #71 in the near future. I believe that kurobako-go accelerate the development of goptuna (and optuna). Thanks!

P.S. it seems you noticed, I created https://github.com/c-bata/github-actions-kurobako. This can be also useful at Optuna.

**Comment by sile** [comment]
Thank you for reviewing and using kurobako-go!
sile/kurobako-go#2 seems good, so I just merged the PR.

> It seems you've already noticed, I created https://github.com/c-bata/github-actions-kurobako. This might be also useful at Optuna.

Yeah, `github-actions-kurobako` seems very interesting. I have wanted to introduce continuous benchmarking into the Optuna development process, and I hope that `github-actions-kurobako` could be used to achieve this goal.

**Comment by c-bata** [comment]
Thank you for merging the PR. I close this issue.

> Yeah, github-actions-kurobako seems very interesting. I have wanted to introduce continuous benchmarking into the Optuna development process, and I hope that github-actions-kurobako could be used to achieve this goal.

Let's discuss it at our next meeting 👍
