### ISSUE TITLE
Passing other variables to objective function?

### ISSUE THREAD

**Issue by nsauerwald** [c-bata/goptuna#65]
Forgive me if there is an obvious answer, but is it possible to define an objective function that depends on other variables? It doesn't seem possible to pass variables to the objective function itself, and as a separate function it cannot access previously declared variables. 

Here is a very minimal example: say my objective function is (x1-2)^2 + (x2+5)^2 + a, where "a" is read from a file or input by a user. How can I optimize this objective with goptuna?

**Comment by c-bata** [comment]
Hi @nsauerwald 

You can define your objective function as the method.

```go
package main

import (
	"log"
	"math"

	"github.com/c-bata/goptuna"
	"github.com/c-bata/goptuna/tpe"
)

type Foo struct {
	A float64
}

func (f *Foo) Objective(trial goptuna.Trial) (float64, error) {
	x1, _ := trial.SuggestUniform("x1", -10, 10)
	x2, _ := trial.SuggestUniform("x2", -10, 10)
	return math.Pow(x1-2, 2) + math.Pow(x2+5+f.A, 2), nil
}

func main() {
	study, err := goptuna.CreateStudy(
		"goptuna-example",
		goptuna.StudyOptionSampler(tpe.NewSampler()),
	)
	if err != nil {
		log.Fatal("failed to create study:", err)
	}

	foo := &Foo{A: 5}
	if err = study.Optimize(foo.Objective, 50); err != nil {
		log.Fatal("failed to optimize:", err)
	}

	v, _ := study.GetBestValue()
	params, _ := study.GetBestParams()
	log.Printf("Best evaluation=%f (x1=%f, x2=%f)",
		v, params["x1"].(float64), params["x2"].(float64))
}
```


And you can also define your objective function as the inner function like:

```go
func main() {
    a := 5
    objective := func(trial goptuna.Trial) (float64, error) {
        ...
    }
}
```

**Comment by c-bata** [comment]
I close this. Please feel free to reopen if you have more questions.
